function Long_horizon_phase_attribution_self_test()
%LONG_HORIZON_PHASE_ATTRIBUTION_SELF_TEST Deterministic ABGMR checks.

    rng(26020, 'twister');
    n = 180;
    dates = datetime(2002, 1, 3) + calmonths((0:n-1)');
    pre = dates <= datetime(2008, 8, 7);

    timing = randn(n, 1);
    fg = randn(n, 1);
    qe = randn(n, 1);
    qe(pre) = 0.04 * qe(pre);
    truth = [timing, fg, qe];
    loadings = [0.45, 0.00, 0.00; ...
        0.82, 0.18, 0.00; ...
        1.00, 0.38, 0.04; ...
        0.86, 0.72, 0.10; ...
        0.51, 1.00, 0.28; ...
        0.20, 0.79, 0.72; ...
        0.08, 0.42, 1.00];
    Xpc = truth * loadings' + 0.003 * randn(n, 7);
    [pcScores, pcFit] = Step26_abgmr_factors(Xpc, dates, "PC", ...
        datetime(2008, 8, 7));

    association = abs(corr(pcScores, truth));
    assert(association(1, 1) > 0.98 && association(2, 2) > 0.95 && ...
        association(3, 3) > 0.95, ...
        'STEP26_SELFTEST_RECOVERY: conference factors were not recovered.');
    assert(pcFit.max_anchor_error < 1e-10, ...
        'STEP26_SELFTEST_ANCHOR: conference anchor normalisation failed.');
    assert(pcFit.max_zero_1m_loading < 1e-10, ...
        'STEP26_SELFTEST_ZERO: FG/QE must have zero 1M loadings.');
    assert(pcFit.qe_pre_second_moment <= pcFit.fg_pre_second_moment + 1e-12, ...
        'STEP26_SELFTEST_QE: QE must minimise pre-crisis variation.');
    applied = Step26_apply_abgmr_fit(Xpc, pcFit);
    assert(max(abs(applied - pcScores), [], 'all') < 1e-10, ...
        'STEP26_SELFTEST_APPLY: frozen fit does not reproduce fitted scores.');

    target = randn(n, 1);
    nuisance = randn(n, 2);
    prTruth = [target, nuisance];
    prLoadings = [1.00, 0.00, 0.00; ...
        0.78, 0.12, 0.03; ...
        0.61, 0.18, 0.05; ...
        0.43, 0.23, 0.08; ...
        0.25, 0.31, 0.12; ...
        0.08, 0.39, 0.25; ...
        0.02, 0.28, 0.42];
    Xpr = prTruth * prLoadings' + 0.003 * randn(n, 7);
    [prScores, prFit] = Step26_abgmr_factors(Xpr, dates, "PR", ...
        datetime(2008, 8, 7));
    assert(abs(corr(prScores, target)) > 0.98 && ...
        prFit.max_anchor_error < 1e-10, ...
        'STEP26_SELFTEST_TARGET: Target recovery or normalisation failed.');

    [scaledScores, scaledFit] = Step26_abgmr_factors(2 * Xpc, dates, ...
        "PC", datetime(2008, 8, 7));
    assert(max(abs(scaledScores - 2 * pcScores), [], 'all') < 1e-8 && ...
        max(abs(scaledFit.loadings - pcFit.loadings), [], 'all') < 1e-8, ...
        'STEP26_SELFTEST_UNITS: factor construction is not unit equivariant.');

    fprintf(['Long_horizon_phase_attribution_self_test: ABGMR rotation, ' ...
        'anchors, frozen application and unit-equivariance checks passed.\n']);
end
