function manifest = Require_window_semantics_manifest(projectRoot)
%REQUIRE_WINDOW_SEMANTICS_MANIFEST Gate phase windows on certified semantics.

    if nargin < 1 || strlength(string(projectRoot)) == 0
        projectRoot = Get_project_root();
    end
    manifestFile = fullfile(projectRoot, 'Output', 'manifests', ...
        'window_semantics_manifest.csv');
    if exist(manifestFile, 'file') ~= 2
        error(['WINDOW_SEMANTICS_MANIFEST_MISSING: run ' ...
            'Window_semantics_certification before phase-window construction.']);
    end

    manifest = readtable(manifestFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    required = ["schema_version", "status", "raw_time_zone", ...
        "analysis_time_zone", "bar_label_status", "bar_label_semantics", ...
        "canonical_bar_time"];
    missing = required(~ismember(required, string(manifest.Properties.VariableNames)));
    if ~isempty(missing) || height(manifest) ~= 1
        error('WINDOW_SEMANTICS_MANIFEST_INVALID: malformed %s.', manifestFile);
    end

    allowedSemantics = ["interval_start", "interval_end"];
    ok = manifest.schema_version(1) == "window_semantics_v1" & ...
        manifest.status(1) == "certified" & ...
        manifest.raw_time_zone(1) == "America/Chicago" & ...
        manifest.analysis_time_zone(1) == "UTC" & ...
        manifest.bar_label_status(1) == "certified" & ...
        ismember(manifest.bar_label_semantics(1), allowedSemantics) & ...
        manifest.canonical_bar_time(1) == "interval_end_utc";
    if ~ok
        error('WINDOW_SEMANTICS_MANIFEST_MISMATCH: certification did not pass.');
    end
end
